test_that("冻结分析规格通过结构和规则注册校验", {
  plan <- load_analysis_plan()
  expect_identical(as.character(plan$standards$adam), "2.1")
  expect_identical(as.character(plan$standards$admiral), "1.5.0")
  expect_identical(as.character(plan$standards$r2rtf), "1.3.1")
  expect_length(analysis_variable_names(plan, "ADSL"), 19L)
})

test_that("三域模拟 SDTM 满足预期维度", {
  datasets <- demo_sdtm_datasets()
  expect_equal(dim(datasets$DM), c(6L, 18L))
  expect_equal(dim(datasets$AE), c(9L, 17L))
  expect_equal(dim(datasets$VS), c(60L, 16L))
})

test_that("ADSL 与 ADAE 按冻结规则派生并通过本地检查", {
  skip_if_not_installed("admiral", minimum_version = "1.5.0")
  plan <- load_analysis_plan()
  sdtm <- demo_sdtm_datasets()
  adsl <- derive_adsl(sdtm$DM, plan)
  adae <- derive_adae(sdtm$AE, adsl, plan)
  expect_equal(dim(adsl), c(6L, 19L))
  expect_equal(nrow(adae), 9L)
  expect_equal(sum(adae$TRTEMFL == "Y", na.rm = TRUE), 7L)
  expect_equal(sum(is.na(adae$TRTEMFL)), 2L)
  expect_equal(dplyr::n_distinct(adae$USUBJID[!is.na(adae$TRTEMFL) & adae$TRTEMFL == "Y"]), 5L)
  expect_equal(nrow(validate_adam_datasets(list(ADSL = adsl, ADAE = adae), sdtm, plan)), 0L)
})

test_that("两张表的分母和治疗中出现事件总体行正确", {
  skip_if_not_installed("admiral", minimum_version = "1.5.0")
  plan <- load_analysis_plan()
  sdtm <- demo_sdtm_datasets()
  adsl <- derive_adsl(sdtm$DM, plan)
  adae <- derive_adae(sdtm$AE, adsl, plan)
  demographics <- demographic_table_object(adsl, plan)
  teae <- teae_table_object(adsl, adae, plan)
  expect_identical(as.integer(demographics$denominators), c(2L, 4L, 6L))
  expect_identical(as.integer(teae$denominators), c(2L, 4L, 6L))
  expect_identical(teae$data[["Placebo (N=2)"]][[1L]], "1 (50.0%)")
  expect_identical(teae$data[["Trace Drug 10 mg (N=4)"]][[1L]], "4 (100.0%)")
  expect_identical(teae$data[["Total (N=6)"]][[1L]], "5 (83.3%)")
})

test_that("表格由同一结果对象输出 CSV、HTML 和 RTF", {
  skip_if_not_installed("admiral", minimum_version = "1.5.0")
  skip_if_not_installed("r2rtf", minimum_version = "1.3.1")
  plan <- load_analysis_plan()
  sdtm <- demo_sdtm_datasets()
  adsl <- derive_adsl(sdtm$DM, plan)
  adae <- derive_adae(sdtm$AE, adsl, plan)
  config <- demo_analysis_config(file.path(tempdir(), paste0("trace-tlf-", sample.int(1e8, 1L))))
  ensure_output_directories(config)
  objects <- list(
    `T14.1.1` = demographic_table_object(adsl, plan),
    `T14.3.1` = teae_table_object(adsl, adae, plan)
  )
  manifest <- purrr::map_dfr(objects, write_table_object, config = config)
  expect_equal(nrow(manifest), 2L)
  paths <- unlist(manifest[c("csv_path", "html_path", "rtf_path")], use.names = FALSE)
  expect_true(all(file.exists(paths)))
  expect_true(all(file.info(paths)$size > 0L))
  issues <- table_validation_issues(objects, list(ADSL = adsl, ADAE = adae), config)
  expect_equal(nrow(issues), 0L)
})

test_that("ADaM CSV 与 XPT 可以回读且结构保持一致", {
  skip_if_not_installed("admiral", minimum_version = "1.5.0")
  plan <- load_analysis_plan()
  sdtm <- demo_sdtm_datasets()
  datasets <- list(ADSL = derive_adsl(sdtm$DM, plan))
  datasets$ADAE <- derive_adae(sdtm$AE, datasets$ADSL, plan)
  config <- demo_analysis_config(file.path(tempdir(), paste0("trace-adam-", sample.int(1e8, 1L))))
  ensure_output_directories(config)
  manifest <- purrr::imap_dfr(datasets, ~ write_adam_dataset(.x, .y, plan, config))
  reread <- load_adam_datasets(config)
  expect_equal(nrow(manifest), 2L)
  expect_identical(names(reread$ADSL), analysis_variable_names(plan, "ADSL"))
  expect_identical(names(reread$ADAE), analysis_variable_names(plan, "ADAE"))
  expect_s3_class(reread$ADSL$TRTSDT, "Date")
  expect_equal(nrow(validate_adam_datasets(reread, sdtm, plan)), 0L)
})
