community:
  expected_version: 4.2.0.5013
  executable: ''
  java: ''
  client_jar: ''
  client_version: 1.0.9
  config_root: ''
validation:
  engine_version: 2508.1
  engine_name: FDA 2508.1
  filter: FDA
  standard: SDTM
  standard_version: '3.4'
  controlled_terminology_version: '2026-03-27'
  report_cutoff: 100
  java_initial_memory: 256m
  java_max_memory: 2048m
scope:
  generated_domains:
    - DM
    - AE
    - VS
  omitted_domains:
    - TS
    - TA
    - TE
    - TV
    - TI
    - SE
    - SV
    - DS
    - EX
    - CM
    - LB
    - MH
    - SC
    - QS
    - RELREC
  define_xml_in_scope: false
