version: '1.0.0'
sets:
  vs_standard_v1:
    - {test_code: HEIGHT, from_unit: cm, to_unit: cm, multiplier: 1, offset: 0, round_digits: 1}
    - {test_code: HEIGHT, from_unit: in, to_unit: cm, multiplier: 2.54, offset: 0, round_digits: 1}
    - {test_code: WEIGHT, from_unit: kg, to_unit: kg, multiplier: 1, offset: 0, round_digits: 1}
    - {test_code: WEIGHT, from_unit: LB, to_unit: kg, multiplier: 0.45359237, offset: 0, round_digits: 1}
    - {test_code: TEMP, from_unit: C, to_unit: C, multiplier: 1, offset: 0, round_digits: 1}
    - {test_code: TEMP, from_unit: F, to_unit: C, multiplier: 0.555555555555556, offset: -17.7777777777778, round_digits: 1}
    - {test_code: SYSBP, from_unit: mmHg, to_unit: mmHg, multiplier: 1, offset: 0, round_digits: 1}
    - {test_code: DIABP, from_unit: mmHg, to_unit: mmHg, multiplier: 1, offset: 0, round_digits: 1}
    - {test_code: PULSE, from_unit: beats/min, to_unit: beats/min, multiplier: 1, offset: 0, round_digits: 0}
unit_aliases:
  centimeters: cm
  centimeter: cm
  inches: in
  inch: in
  kilograms: kg
  kilogram: kg
  lb: LB
  lbs: LB
  pounds: LB
  pound: LB
  degC: C
  degF: F
